# Generated by Django 5.1.2 on 2024-10-22 14:59

import django.db.models.deletion
import vehicle.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "license_plate",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[vehicle.validators.LicensePlateValidator()],
                        verbose_name="license plate",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
            },
        ),
    ]
